#!/bin/bash
#
# Si tu lis ceci, c'est que tu t'es aventuré en dehors des limites,
# et es en train de lire le code de ce jeu.
#
#                    Félicitations!
#
# C'est ta curiosité qui te permettra d'apprendre Linux. Lis ce code 
# et essaie de voir si tu peux le comprendre.
#
# Lorsque tu sera prêt à reprendre le jeux, alors, concentre toi sur 
# les parchemins.
#

if ! grep  --only-matching amulette <<< $I &> /dev/null; then
    printf "\n"
    echo "Tu as trouvé une **amulette** en émeraude !"
    printf "\n"
    echo "Pour récuperer le trésor, tu dois avoir une variable pour stocker ton inventaire."
    printf "\n"
    echo "Crée une variable et ajoutes-y ton trésor de la mnaière suivante:"
    printf "\n"
    echo "export I=amulette,\$I"
    printf "\n"
    echo "Tu peux à tout moment contempler tes richesses avec cette commande:"
    printf "\n"
    echo "echo \$I"
    printf "\n"
    mv ../.chapelle ../chapel 2>/dev/null
    mv ../.caveau ../caveau 2>/dev/null
    mv ../.feraille ../feraille 2>/dev/null
else
    echo "Ce trésor a déjà été pris!"
fi


















































































































































































































































































# Hmm, that didn't work.
# Try moving into the armoury, maybe you
# can come back to this treasure later!


