#!/bin/bash
#
# Si tu lis ceci, c'est que tu t'es aventuré en dehors des limites,
# et es en train de lire le code de ce jeu.
#
#                    Félicitations!
#
# C'est ta curiosité qui te permettra d'apprendre Linux. Lis ce code
# et essaie de voir si tu peux le comprendre.
#
# Lorsque tu sera prêt à reprendre le jeux, alors, concentre toi sur
# les parchemins.
#
echo "In the corner is a decaying old altar of some forgotten god."
printf "\n"
echo "There is a small trinket on the ground."
echo "It looks religious in nature."
echo "Do you want to put the trinket back on the altar?"
printf "\n"
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
   echo "You place the trinket upon the altar."
   echo "You feel a gentle breeze pass through the room."
   touch .bless
else
   echo "Do you want to take the trinket for yourself?"
   read RESP
   if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
       echo "Remember to add the trinket to your inventory!"
       touch .curse
   else
   echo "You leave the trinket where it lies."
   echo "There is a great sadness here."
   echo "You feel compelled to move on."
   touch .curse
   fi
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./altar
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F
