#!/bin/bash
#
# Si tu lis ceci, c'est que tu t'es aventuré en dehors des limites,
# et es en train de lire le code de ce jeu.
#
#                    Félicitations!
#
# C'est ta curiosité qui te permettra d'apprendre Linux. Lis ce code
# et essaie de voir si tu peux le comprendre.
#
# Lorsque tu sera prêt à reprendre le jeux, alors, concentre toi sur
# les parchemins.
#
if [ -e drum ]; then
   echo "War drums pound in the distance,"
   echo "giving Nyarlathotep strength."
   printf "\n"
   echo "If you know a spell to un-summon the drums,"
   echo "Nyarlathotep would probably weaken!"
   echo "Look up the *mv* command."
else
   echo "The drumming has stopped."
   echo "Now's your chance to attack!"
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./drummer
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F
