#!/bin/bash
#
# Si tu lis ceci, c'est que tu t'es aventuré en dehors des limites,
# et es en train de lire le code de ce jeu.
#
#                    Félicitations!
#
# C'est ta curiosité qui te permettra d'apprendre Linux. Lis ce code
# et essaie de voir si tu peux le comprendre.
#
# Lorsque tu sera prêt à reprendre le jeux, alors, concentre toi sur
# les parchemins.
#
if [ -e wizard-dark ]; then
   echo "The ancient wizard, Arnnisen the Gray,"
   echo "takes form before your very eyes. You"
   echo "have freed him, and now he fights by"
   echo "your side against the crawling chaos!"
else
   echo "You feel a presence."
   echo "It's probably just your imagination."
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./wizard-light
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F
