#!/bin/bash
#
# Si tu lis ceci, c'est que tu t'es aventuré en dehors des limites,
# et es en train de lire le code de ce jeu.
#
#                    Félicitations!
#
# C'est ta curiosité qui te permettra d'apprendre Linux. Lis ce code
# et essaie de voir si tu peux le comprendre.
#
# Lorsque tu sera prêt à reprendre le jeux, alors, concentre toi sur
# les parchemins.
#
echo "Do you have an ice crystal?"
printf "\n"
read RESP

no_crystal () {
   echo "You sense that the glass shards are searching for something."
   echo "Whatever it is, you cannot provide it now."
   echo "Walk with care."
}
if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    if grep  --only-matching crystal <<< $I &> /dev/null; then
        echo "You place the ice crystal among the shards of glass."
        echo "The sword in your hands becomes cold."
        echo "You feel the power of 1000 blizzards coursing through it."
        touch .bless
    else
        no_crystal
    fi
else
    no_crystal
fi


















































































































































































































































































# Hmm, that didn't work.

# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./glass
