#!/bin/bash
#
# Si tu lis ceci, c'est que tu t'es aventuré en dehors des limites,
# et es en train de lire le code de ce jeu.
#
#                    Félicitations!
#
# C'est ta curiosité qui te permettra d'apprendre Linux. Lis ce code
# et essaie de voir si tu peux le comprendre.
#
# Lorsque tu sera prêt à reprendre le jeux, alors, concentre toi sur
# les parchemins.
#


gameover () {
    echo "You see the corpse of a slain adventurer on the floor of the dungeon." > corpse
    echo "You find the following items on the corpse:  " >> corpse
    echo >> corpse
    echo $I >> corpse
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}

penguin_bite () {
	echo "The penguin gnaws at your Bag of Holding, hoping for a morsel."
	echo "Finding nothing, it takes a nip at your hand"
	echo 'for 1 point of damage. (let "HP=HP-1").'
	echo "You may avoid this damage if you have a sword"
	echo "and wish to attack the penguin."
	printf "\n"
	echo "Do you want to attack the penguin?"
	read RESP
	if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
	    echo "You attack the penguin, quickly doing away with it with one quick slash."
	    echo "This draws the attention of the other penguins in the room."
	    echo "They band together and rush at you. You fight your best."
        let HP=HP-5
        export HP
        if [ "$HP" -le 0 ]; then
            echo "The mob of penguins reduces your hit points to zero."
            echo "You are slain by the mob."
            gameover
            exit 1
        else
	        echo "But a mob of penguins does not tolerate oppression, and you soon find yourself sealed in a block of ice."
	        echo "There you stay, perfectly preserved for 128 years. When you are thawed, you may continue your adventure."
        fi
	else
        let HP=HP--
        export HP
	    echo "You keep things in perspective, and do not lash out at the penguin."
	fi
}

echo "One of the birds finally notices your presence."
echo "It turns its head sideways, seemingly beckoning"
echo "for you to come closer."
printf "\n"
echo "Do you get closer?"
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
   echo "You take a step forward, and the bird rushes"
   echo "toward you, its mouth open wide."
   echo "Do you happen to have a fish?"
   read RESP

    if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
        if grep  --only-matching fish <<< $I; then
            echo "You toss the fish at the penguin,"
            echo "which catches the fish mid-air and"
            echo "gobbles it down."
            echo
            echo "Don't forget to remove the fish from your inventory."
            echo "Try the following command:"
            echo
            echo 'export I=`sed "s/fish//; s/,,/,/" <<< $I`'
        else
            echo "You don't have a fish!"
            echo
            penguin_bite
        fi
   else
        penguin_bite
   fi

else
   echo "You back away from the penguin carefully."
   echo "It loses interest in you and waddles away."
fi
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
##
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Well that didn't work!
