#!/bin/bash
#
# Si tu lis ceci, c'est que tu t'es aventuré en dehors des limites,
# et es en train de lire le code de ce jeu.
#
#                    Félicitations!
#
# C'est ta curiosité qui te permettra d'apprendre Linux. Lis ce code
# et essaie de voir si tu peux le comprendre.
#
# Lorsque tu sera prêt à reprendre le jeux, alors, concentre toi sur
# les parchemins.
#
echo "Runes, the language of the ancient mystics that once ruled"
echo "this land, are inscribed upon the western wall."
echo "Do you want to read them?"
read RESP
if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
   echo "You recall the lessons of Caitlyn the Green,"
   echo "who taught you these ancient letters."
   printf "\n"
   echo "The runes are instructions on how to summon"
   echo "a portal that will allow you to walk through"
   echo "an invisible door contained in the wall."
   printf "\n"
   echo "In Bash, a symlink is an *alias* or a *shortcut*"
   echo "to another file or directory."
   echo "Create one from this room to the adjacent one:"
   echo "ln -f -s `pwd`/../../../chapel/courtyard/aviary/hall portal"
   printf "\n"
else
   echo "You decide it is probably best to leave"
   echo "magickal enscriptions as they are."
fi



























































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./spell
