#!/bin/bash
#
# Si tu lis ceci, c'est que tu t'es aventuré en dehors des limites,
# et es en train de lire le code de ce jeu.
#
#                    Félicitations!
#
# C'est ta curiosité qui te permettra d'apprendre Linux. Lis ce code
# et essaie de voir si tu peux le comprendre.
#
# Lorsque tu sera prêt à reprendre le jeux, alors, concentre toi sur
# les parchemins.
#
echo
if ! grep  --only-matching coins <<< $I &> /dev/null; then
    echo "You have found a stash of **coins**!"
    echo "They are old and worn with age,"
    echo "but they still gleam in the magical light"
    echo "emanating from your eyes."
    printf "\n"
    echo "Prepend this item to your inventory:"
    printf "\n"
    echo '$ export I=coins,$I'
    printf "\n"
    echo "Remember, you can check your inventory:"
    printf "\n"
    echo 'echo $I'
    printf "\n"
else
    echo "This treasure has already been taken."
fi








































































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./treasure
