#!/bin/bash
#
# Si tu lis ceci, c'est que tu t'es aventuré en dehors des limites,
# et es en train de lire le code de ce jeu.
#
#                    Félicitations!
#
# C'est ta curiosité qui te permettra d'apprendre Linux. Lis ce code 
# et essaie de voir si tu peux le comprendre.
#
# Lorsque tu sera prêt à reprendre le jeux, alors, concentre toi sur 
# les parchemins.
#
printf "\n"
echo "You have found a gleaming silver **sword**!"
echo "You marvel at its craftmanship, and you recall"
echo "tales from your childhood of the great"
echo "mystic king Rannismir who bore such a sword to"
echo "protect the kingdom from undead."
printf "\n"
echo "Add this item to your inventory:"
printf "\n"
echo "$ export I=sword,\$I"
printf "\n"
echo "Remember, you can check your inventory:"
printf "\n"
echo "echo \$I"
printf "\n"
mv ../../.chapelle ../../chapelle 2>/dev/null
mv ../../.caveau ../../caveau 2>/dev/null
mv ../../.feraille ../../feraille 2>/dev/null























































































































































































































































































# Hmm, ça n'a pas fonctionné !
#
# Peut être le parchemin peut te mettre sur la voie.

